version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: sudo python -m pip install --upgrade pip
      - run:
          name: Install pip requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: nosetests --with-coverage --with-xunit
      - run:
          name: Build distributable packages
          command: python setup.py sdist bdist_wheel
      - run:
          name: Validate PiPy requirements
          command: twine check dist/*
      - run:
          name: Upload code coverage
          command: codecov
