version: 2
orbs:
  codecov: codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run: sudo python -m pip install --upgrade pip
      - run: sudo pip install -r requirements.txt
      - run: nosetests
