version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
           name: Preparing environment
           shell: /bin/sh
           command: |
             mkdir -p test-results/nodetests
             mkdir -p test-results/pylint
      - run:
          name: Upgrade pip
          command: sudo python -m pip install --upgrade pip
      - run:
          name: Install pip requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run lint tests
          shell: /bin/sh
          command: |
            pylint --output-format=pylint_junit.JUnitReporter --exit-zero libcloudns/ > test-results/pylint/results.xml
            pylint libcloudns
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: dist/