version: 2.1

orbs:
  pylint: qventus/python-lint@0.0.6

jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
           name: Upgrade pip
           command: sudo python -m pip install --upgrade pip
      - run:
           name: Install pip requirements
           command: sudo pip install -r requirements.txt
      - pylint/lint:
          pyversion: 3.8.0
          checkout: false
          compare-to-pr-root: false