version: 2
orbs:
  codecov: codecov@1.0.2
jobs:
  build:
    docker:
      - image: python:3-slim
    steps:
      - checkout
      - codecov/upload
          file: {{ coverage_report_filepath }}
          token: ${CODECOV_TOKEN}
