version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
          name: Preparing environment
          shell: /bin/sh
          command: |
            mkdir -p test-results/nodetests
            mkdir -p test-results/pylint
      - python/install-deps
      - run:
          name: Run lint tests
          shell: /bin/sh
          command: |
            pylint --output-format=pylint_junit.JUnitReporter --exit-zero libcloudns/ > test-results/pylint/results.xml
            pylint libcloudns/
      - run:
          name: Run unit tests
          command: nosetests --with-coverage --with-xunit          --xunit-file="test-results/nodetests/results.xml"
      - run:
          name: Build packages
          command: python setup.py sdist bdist_wheel
      - run:
          name: Validate packages
          command: twine check dist/*
      - codecov/upload
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: dist/
      - store_artifacts:
          path: test-results/
